language: cpp

env:

os:
  - osx
  - linux

install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install gsed automake autoconf libtool; fi

before_script:
  - autoreconf -i -I/usr/share/gnulib/m4 -I `pwd`/m4

script:
  - ./configure && make && ./foo

branches:
  only:
    - master

notifications:
  email:
    on_success: change
    on_failure: always