environment:
  matrix:
    - GENERATOR: "Visual Studio 12"
    - GENERATOR: "Visual Studio 12 Win64"

build_script:
  - cmake "-G%GENERATOR%" -H. -B_builds
  - cmake --build _builds

test_script:
  - ps: cd _builds
  - ctest -VV
